export enum ErrorCode {
  EMAIL_USED = 'EMAIL_USED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  TODO_NOT_FOUND = 'TODO_NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
}
